### PR TITLE
Removed the `load_dotenv` package / Refactoring

### PR DESCRIPTION
**Pull request by ejach**
- Removed the `load_dotenv` package for simplicity
- Refactored code and documentation to reflect this

### CODE REVIEW

**Comment by mveinot** [comment]
How is one intended to set the environment variables so that the script can access them, if we're just dropping the .py file in /etc/update-motd.d? Or are you suggesting it to be called from a bash script going forward?

**Comment by ejach** [comment]
I put a tutorial in the `README.md` that links to
https://help.ubuntu.com/community/EnvironmentVariables
I just found that having that package is pointless if you can just move
away from the `.env` file entirely and just rely on the system environment
variables, and I feel it is a little more secure this way rather than
having a file with the credentials.
If you think this is a little too in-depth, I completely understand.

**Comment by mveinot** [comment]
I'm not necessarily opposed to the change, but I'm struggling to understand _where_ in the system the environment variables must be set so that the python script will see them when it runs via update-motd.

**Comment by ejach** [comment]
I see where you are coming from now.
From my understanding, before this change, the `.env` file was handling the credentials and emulating pulling this data from the environment using the `load_dotenv` package.
But, this middleman that relies on a package could be eliminated if the credentials are stored in the system environment itself rather than a `.env` file.
These environment variables can be persisted when the system is rebooted by editing the `~/.bashrc` or `/etc/environment`.
Does this clear up anything?

**Comment by mveinot** [comment]
Okay - I have tested this and it works - just need to make the instructions to put the variables in /etc/environment explicit and since they're going to be system-visible, they should be changed to `plex_server` and `plex_port` to match `plex_token` so as not to interfere with anything else that might use simply "server" and "port"

**Comment by ejach** [comment]
Alright, I will do that and commit the changes 👍

**Comment by ejach** [comment]
Does this look sufficient?

**Comment by mveinot** [comment]
I think so, will merge it, thanks!

**Comment by ejach** [comment]
Hi, so I have exposed my IP on my branch
https://github.com/mveinot/plex-motd/blob/274ab834ad175ce6f5cc56f752464998bdfdc0dc/.env
I have fixed everything on my end, so could you please follow the
instructions below to purge my IP from the repo?
Sorry for the inconvenience,
Evan

---------- Forwarded message ---------
From: GitHub Developer Support ***@***.***>
Date: Mon, Apr 25, 2022 at 5:33 PM
Subject: [GitHub Support] - Remove sensitive data from commit
To: Evan J ***@***.***>


## Please do not write below this line ##

Your request (Ticket 1599815 <https://support.github.com/ticket/1599815>)
has been updated.

To review the status of your request and add additional comments, please
visit: Ticket 1599815 <https://support.github.com/ticket/1599815>.

*GitHub* (GitHub Support)

Apr 25, 2022, 9:33 PM UTC

Hi Evan,

Thanks for reaching out to GitHub Support!

The way that removing unwanted or sensitive data from a repository works is
that the commit that first introduced the data needs to be completely
unreferenced in branches, tags and pull requests.

A single reference anywhere will prevent garbage collection from being able
to purge the data completely. Because merging a commit into a branch makes
it part of the history of your repo, every pull request involving that
branch created after that moment will reference that history.

Our tooling shows SHA 274ab834ad175ce6f5cc56f752464998bdfdc0dc is
referenced in the following areas:

   - mveinot/plex-motd
      - master
      - https://github.com/mveinot/plex-motd/pull/22 (Pull request)
   - ejach/plex-motd
      - revert-21-revert-20-master

Regarding the reference in your master branch, short of deleting the
branch, you can completely remove unwanted or sensitive data using the BFG
Repo-Cleaner or the git filter-repo command. We've got a help article that
describes both options in further detail here
<https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository>.
You will need to contact the repository admin concerning this part of the
process.

Regarding ejach/plex-motd, if you are able to contact the owner of that
repository, you could suggest that they either complete the steps outlined
above themselves, or delete and re-fork the repository once the operation
has been carried out for mveinot/plex-motd.

Once the steps have been completed for the contaminated branch and the
fork, please let us know and we'll get that pull request sorted, and clear
the repository cache on our end. Please note that we will require admin
approval for those latter two operations (they can simply be CC'ed to this
exchange, or write in separately).

Meanwhile, please feel free to reach out with any questions you might have.

Best regards,

Allan H

GitHub Support
------------------------------

ℹ️.Find answers to common questions and learn with other GitHub users in
our GitHub Community Forum <https://github.community/>ℹ️

*Evan J*

Apr 25, 2022, 8:15 PM UTC

Hi, I tried following your help support page about this, but I would like
to remove this commit from the repository:
https://github.com/mveinot/plex-motd/blob/274ab834ad175ce6f5cc56f752464998bdfdc0dc/.env
Please point me in the right direction to remove this please.
Thanks,
Evan

This email is a service from GitHub Support.
[DEL7V9-3WRPR]

**Comment by mveinot** [comment]
I wasn't able to get the directions to actually purge it, so I deleted the
commit history and just rebased it on my current source

Cheers,
Mark Veinot
+19026708604
***@***.***

**Comment by ejach** [comment]
Hi again,
The GitHub staff need permission to do the following:

We'll need owner or admin approval for these two final operations:

   - Permission to delete PRs 22 and 23 (or their internal refs only) for
   mveinot/plex-motd
   - Permission to permanently purge the contents of ejach/plex-motd


Is that ok with you?
Thanks for being so helpful throughout this process.

**Comment by mveinot** [comment]
Yes, this is okay with me - do I have to do anything to grant permission?
or is replying in the affirmative to this email sufficient?

Cheers,
Mark Veinot
+19026708604
***@***.***

**Comment by ejach** [comment]
I think the reply to the email should suffice, I will let you know.
Thanks again!

**Pull request merged**
